import math


# Quantities in SI units
METER_SI = 1
CM_SI = 1e-2
NM_SI = 1e-9
SECOND_SI = 1
Q_E_SI = 1.60217663e-19
EV_SI = Q_E_SI
M_E_SI = 9.1093837e-31
VOLT_SI = 1
KELVIN_SI = 1
K_B_SI = 1.38064852e-23
H_BAR_SI = 1.054571817e-34  # J s
H_SI = H_BAR_SI * 2 * math.pi
EPSILON_0_SI = 8.8541878128e-12

# Defining our own units
NM = 1
Q_E = 1
EV = 1
M_E = 1

# Calculating how each dimension needs to be scaled to go from SI units to
# our own
DISTANCE_SCALING = NM / NM_SI
CHARGE_SCALING = Q_E / Q_E_SI
ENERGY_SCALING = EV / EV_SI
MASS_SCALING = M_E / M_E_SI
TIME_SCALING = math.sqrt(MASS_SCALING * DISTANCE_SCALING**2 / ENERGY_SCALING)
VOLTAGE_SCALING = ENERGY_SCALING / CHARGE_SCALING
K_B_SCALING = DISTANCE_SCALING**2 * MASS_SCALING / TIME_SCALING**2
ACTION_SCALING = ENERGY_SCALING * TIME_SCALING

# Converting the quantities given in SI units above to our units
METER = METER_SI * DISTANCE_SCALING
CM = CM_SI * DISTANCE_SCALING
SECOND = SECOND_SI * TIME_SCALING
VOLT = VOLT_SI * VOLTAGE_SCALING
K_B = K_B_SI * K_B_SCALING
KELVIN = KELVIN_SI * ENERGY_SCALING / K_B_SCALING
H_BAR = H_BAR_SI * ACTION_SCALING
H = H_SI * ACTION_SCALING
EPSILON_0 = EPSILON_0_SI * CHARGE_SCALING / VOLTAGE_SCALING / DISTANCE_SCALING
